### ISSUE TITLE
No lineage if drop table statements

### ISSUE THREAD

**Issue by lehtomar** [ptarmiganlabs/butler-spyglass#34]
**Describe the bug**
No lineage info if tables have been dropped in load script.

**To Reproduce**
Run Butler spyglass with apps that have Drop table statements

**Expected behavior**
Get lineage of tables that have been dropped from script.

**Screenshots**

**Describe environment:**
 - OS: Windows Server 2016
 - Containerisation: no
 - Version of Butler Spyglass used: master
 - Command used to start Butler Spyglass: node index.js

**Config file(s)**
What's the content of the config file(s) you use? 
Please make sure to remove all sensitive information before posting it here.

Default config files.

**Additional context**
Tested with QS Nov 2019

**Comment by mountaindude** [comment]
Cleaning up old issues as part of a resurrection of Butler Spyglass.
----------

Not much to do about this I am afraid, given how Qlik Sense works.
In theory it is of course possible to parse the load script or logs and there realise that something was dropped, it's however beyond the current scope of this tool.
